version: '3.9'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-book_manager}
      POSTGRES_USER: ${POSTGRES_USER:-book_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-book_pass}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  web:
    build: .
    environment:
      DEBUG: ${DEBUG:-1}
      SECRET_KEY: ${SECRET_KEY:-dev-secret-key}
      POSTGRES_DB: ${POSTGRES_DB:-book_manager}
      POSTGRES_USER: ${POSTGRES_USER:-book_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-book_pass}
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - .:/app
volumes:
  pgdata:
